_BASE_: "Base-SWINTS_swin.yaml"
MODEL:
  WEIGHTS: "swin_imagenet_pretrain.pth"
  SWINTS:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 2
  REC_HEAD:
    POOLER_RESOLUTION: (16,48)
    RESOLUTION: (32, 80)
    BATCH_SIZE: 128
    NUM_CLASSES: 5463
DATASETS:
  TRAIN: ("rects","art","lsvt","chn_syn",)
  TEST:  ("totaltext_test",)
SOLVER:
  STEPS: (160000,220000)
  MAX_ITER: 260000
  CHECKPOINT_PERIOD: 10000
INPUT:
  FORMAT: "RGB"
