_BASE_: "Base-SWINTS_swin.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  SWINTS:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 2
  REC_HEAD:
    POOLER_RESOLUTION: (16,40)
    RESOLUTION: (32, 80)
    BATCH_SIZE: 128
    NUM_CLASSES: 5463
DATASETS:
  TRAIN: ("rects",)
  TEST:  ("totaltext_test",)
SOLVER:
  STEPS: (140000,160000)
  MAX_ITER: 180000
  CHECKPOINT_PERIOD: 10000
INPUT:
  FORMAT: "RGB"
