_BASE_: "Base-SWINTS_r50.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SWINTS:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 2
DATASETS:
  TRAIN: ("totaltext_train","icdar_2015_train","icdar_2013_train","icdar_2017_validation_mlt","icdar_2017_mlt","icdar_curvesynthtext_train1","icdar_curvesynthtext_train2",)
  TEST:  ("totaltext_test",)
SOLVER:
  STEPS: (360000,420000)
  MAX_ITER: 450000
  CHECKPOINT_PERIOD: 10000
INPUT:
  FORMAT: "RGB"
