_BASE_: "Base-SWINTS_swin.yaml"
MODEL:
  WEIGHTS: ".output/pretrain/model_0449999.pth"
  SWINTS:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 2
DATASETS:
  # TRAIN: ("totaltext_train",)
  TRAIN: ("totaltext_train","icdar_2015_train","icdar_2013_train","icdar_2017_validation_mlt","icdar_2017_mlt",)
  TEST:  ("totaltext_test",)
  # TEST:  ("coco_2017_test-dev",)
SOLVER:
  STEPS: (60000,)
  MAX_ITER: 80000
  CHECKPOINT_PERIOD: 10000
INPUT:
  FORMAT: "RGB"
